import type { SwitchLibraryGame } from './switch-library'

export const PSP_LIBRARY_GAMES: (SwitchLibraryGame & { boxCover?: string; detailCover?: string; cardLanguage?: string; cardGenre?: string })[] = [{
  id: 'tales-of-phantasia-narikiri-dungeon-x',
  title: '幻想传说：换装迷宫X',
  videoUrl: 'https://v.douyin.com/4IklCoDfZXs/',
  cover: '/psp-library/narikiri-dungeon-x/main.webp',
  boxCover: '/psp-library/narikiri-dungeon-x/cover-new.png',
  genre: '角色扮演、动作',
  cardGenre: 'RPG',
  publisher: 'Bandai Namco Games',
  releaseDate: '2010-08-05',
  requiredSystem: '待确认',
  language: '日、中',
  cardLanguage: '中文',
  popularity: 90,
  downloadUrl: 'https://pan.baidu.com/s/1-wXLBASytlJmlRPI62r3xw?pwd=9999',
  description: '跟随双子主角展开幻想冒险，通过更换服装体验不同职业与战斗方式。搭配伙伴探索迷宫，在即时战斗中组合技能，体验《幻想传说》世界的故事。',
  screenshots: Array.from({ length: 8 }, (_, index) => `/psp-library/narikiri-dungeon-x/${String(index + 2).padStart(2, '0')}.webp`),
}, {
  id: 'ridge-racer',
  title: '山脊赛车',
  cover: '/psp-library/ridge-racer/card.jpg',
  detailCover: '/psp-library/ridge-racer/001.jpg',
  boxCover: '/psp-library/ridge-racer/box.png',
  genre: 'RCG',
  publisher: 'Namco',
  releaseDate: '2004.12.12',
  requiredSystem: '待确认',
  language: '日、英、韩',
  cardLanguage: '日文',
  popularity: 100,
  downloadUrl: 'https://pan.baidu.com/s/1pSdu1XeGRhPVNgMIrupP4w?pwd=9999',
  videoUrl: 'https://v.douyin.com/_mbHcSmTHbs/',
  description: '驾驶赛车挑战赛道，在弯道中体验漂移与竞速的乐趣。游戏画面见下方截图。',
  screenshots: [
    '/psp-library/ridge-racer/002.jpg',
    '/psp-library/ridge-racer/OIP-C.webp',
    '/psp-library/ridge-racer/OIP-C (1).webp',
    '/psp-library/ridge-racer/ridgeracertillpsp_18705.jpg',
    '/psp-library/ridge-racer/ridgeracertillpsp_18706.jpg',
    '/psp-library/ridge-racer/ridgeracertillpsp_18709.jpg',
  ],
}, {
  "id": "monster-hunter-portable",
  "title": "怪物猎人 携带版",
  "foreignTitle": "Monster Hunter Portable",
  "cover": "/psp-library/monster-hunter-portable/001.jpg",
  "detailCover": "/psp-library/monster-hunter-portable/001.jpg",
  "boxCover": "/psp-library/monster-hunter-portable/封面图.png",
  "genre": "ACT-动作",
  "cardGenre": "ACT",
  "publisher": "CAPCOM",
  "releaseDate": "2005-12-01",
  "requiredSystem": "待确认",
  "language": "中、日、英、他",
  "cardLanguage": "中文",
  "downloadUrl": "https://pan.baidu.com/s/1ua3xTM1tSvb7Y7nKiMfY8w?pwd=9999",
  "videoUrl": "https://v.douyin.com/jsdk0G71KIQ",
  "updatedAt": "2026-09-24T14:54:36.914Z",
  "description": "2005年发售的《怪物猎人携带版》是系列首款PSP掌机作品，移植自PS2怪物猎人G，以科科特村为据点。本作奠定了掌机4人联机共斗的核心玩法，收录雄火龙、角龙、麒麟等初代经典魔物，拥有下位、上位任务体系，无G级任务与战斗随从猫。系统与动作相对朴素，仅保留基础武器、猫饭与农场功能，是怪物猎人掌机时代的开山原点，主打复古怀旧狩猎体验。",
  "screenshots": [
    "/psp-library/monster-hunter-portable/20d624cb0cf39005109a5fe4e088b2ce.jpg",
    "/psp-library/monster-hunter-portable/OIP-C.webp",
    "/psp-library/monster-hunter-portable/R-C.jpg"
  ]
}, {
  "id": "monster-hunter-portable-2nd",
  "title": "怪物猎人2 携带版",
  "foreignTitle": "Monster Hunter Portable 2nd",
  "cover": "/psp-library/monster-hunter-portable-2nd/001.png",
  "detailCover": "/psp-library/monster-hunter-portable-2nd/001.png",
  "boxCover": "/psp-library/monster-hunter-portable-2nd/封面图.png",
  "genre": "ACT-动作",
  "cardGenre": "ACT",
  "publisher": "CAPCOM",
  "releaseDate": "2007-02-22",
  "requiredSystem": "待确认",
  "language": "中、日、英、他",
  "cardLanguage": "中文",
  "downloadUrl": "https://pan.baidu.com/s/1tnEWUPGqXOV-Bg4HHl5D9A?pwd=9999",
  "videoUrl": "https://v.douyin.com/ZcSP-lrLiiA",
  "updatedAt": "2026-09-24T14:54:36.922Z",
  "description": "怪物猎人 Portable 2》是卡普空 2007 年登陆 PSP 的狩猎动作游戏，承接 MHP1 基础全面升级，掌机怪物猎人系列里程碑作品。\r\n延续无角色等级、依靠装备与操作狩猎巨兽的核心玩法。新增大量全新怪物：轰龙、镰蟹、雪狮子、电龙等经典怪物登场；拓展地图场景，加入雪山、密林昼夜变化。\r\n武器系统扩充，狩猎笛、弓正式完善；任务体系区分村长任务、集会所任务，支持最多 4 人联机协作狩猎。装备打造、素材采集、猫饭系统成型。\r\n相较于初代优化手感、难度梯度，大幅丰富内容量，奠定掌机狩猎多人联机的热度基础，也是很多老猎人的入坑作。",
  "screenshots": [
    "/psp-library/monster-hunter-portable-2nd/1632648886173719.jpg",
    "/psp-library/monster-hunter-portable-2nd/f9bc-kkciesq4733436.jpg",
    "/psp-library/monster-hunter-portable-2nd/OIP-C.webp"
  ]
}, {
  "id": "monster-hunter-portable-2nd-g",
  "title": "怪物猎人2G 携带版",
  "foreignTitle": "Monster Hunter Portable 2nd G",
  "cover": "/psp-library/monster-hunter-portable-2nd-g/001.webp",
  "detailCover": "/psp-library/monster-hunter-portable-2nd-g/001.webp",
  "boxCover": "/psp-library/monster-hunter-portable-2nd-g/封面图.png",
  "genre": "ACT-动作",
  "cardGenre": "ACT",
  "publisher": "CAPCOM",
  "releaseDate": "2008-03-27",
  "requiredSystem": "待确认",
  "language": "中、日、英",
  "cardLanguage": "中文",
  "downloadUrl": "https://pan.baidu.com/s/1mR0e3RvUKPAJYBBJEQ0M1w?pwd=9999",
  "videoUrl": "https://v.douyin.com/M8khZqqz0qM",
  "updatedAt": "2026-09-24T14:54:36.934Z",
  "description": "《怪物猎人 P2G》是 MHP2 的强化 G 级版本，PSP 平台的封神狩猎动作游戏，可继承前作存档。新增 G 级超高难度任务，登场迅龙、崩龙、眠鸟、熔岩龙等大批新怪物与亚种，首次加入战斗艾露猫伙伴，单人也有 AI 随从协助作战。支持四人联机合作狩猎，采集素材打造武器防具，摒弃等级系统，纯粹依靠操作与战术挑战巨型怪物，是无数猎人的青春回忆抖音百科。",
  "screenshots": [
    "/psp-library/monster-hunter-portable-2nd-g/27132019na60.jpg",
    "/psp-library/monster-hunter-portable-2nd-g/310912375cede9YGeEdwCjMx9bm.png",
    "/psp-library/monster-hunter-portable-2nd-g/c4228f921f6ea990d34094d45f84e134.jpg"
  ]
}, {
  "id": "djmax-portable-2",
  "title": "DJMax2 携带版",
  "foreignTitle": "DJ Max Emotional Sense P 2 – Sound Miracle",
  "cover": "/psp-library/djmax-portable-2/1OIP-C.webp",
  "detailCover": "/psp-library/djmax-portable-2/1OIP-C.webp",
  "boxCover": "/psp-library/djmax-portable-2/封面图.png",
  "genre": "MUG-音乐",
  "cardGenre": "MUG",
  "publisher": "PENTAVISION",
  "releaseDate": "2007-03-30",
  "requiredSystem": "待确认",
  "language": "韩",
  "cardLanguage": "韩文",
  "downloadUrl": "https://pan.baidu.com/s/1VGvubJ0zMFCcZJSlgHfGcA?pwd=9999",
  "videoUrl": "https://v.douyin.com/KFpNegMLg-U",
  "updatedAt": "2026-09-24T15:58:00.768Z",
  "description": "《DJMax Portable 2》是系列人气巅峰音游，2007 年发售。新增 5 键、8 键布局与经典 Fever 三倍得分系统，优化长按音符手感；收录 60 余首原创金曲，包含多首系列传世神曲，支持自由任务闯关、双人 WiFi 联机对战。内置商店可解锁音符皮肤、MV、原画等海量收集内容，双语界面友好，难度分层均衡，是无数玩家的 DJMAX 入坑首选。",
  "screenshots": [
    "/psp-library/djmax-portable-2/2R-C1.jpg",
    "/psp-library/djmax-portable-2/43999-menu-DJ-Max-Emotional-Sense-P-2-Limited-Edition.jpg",
    "/psp-library/djmax-portable-2/OIP-C1.webp",
    "/psp-library/djmax-portable-2/R-C.jpg"
  ]
}, {
  "id": "djmax-clazziquai-edition",
  "title": "DJMax3：酷懒之味",
  "foreignTitle": "DJ Max Emotional Sense P – Classiquai Edition",
  "cover": "/psp-library/djmax-clazziquai-edition/1OIP-C1.webp",
  "detailCover": "/psp-library/djmax-clazziquai-edition/1OIP-C1.webp",
  "boxCover": "/psp-library/djmax-clazziquai-edition/封面图.png",
  "genre": "MUG-音乐",
  "cardGenre": "MUG",
  "publisher": "PENTAVISION",
  "releaseDate": "2008-10-24",
  "requiredSystem": "待确认",
  "language": "韩",
  "cardLanguage": "韩文",
  "downloadUrl": "https://pan.baidu.com/s/1si3JooRtb1tikqzgfe8Ndw?pwd=9999",
  "videoUrl": "https://v.douyin.com/EemIlbKcWek",
  "updatedAt": "2026-09-24T15:58:00.776Z",
  "description": "PSP《DJMax 酷懒之味 CE》是 DJMax 系列第三部正统音乐游戏，主打清新治愈轻电子曲风，专为新手优化操作。新增 2 键简易模式，移除高难度 8 键，主线俱乐部巡演模式趣味十足；收录 40 首曲目，支持双人 WiFi 联机对战，可解锁 MV、壁纸、原声等海量收集内容。画风柔和明亮，难度门槛低，是入门 DJMax 的最佳作品。",
  "screenshots": [
    "/psp-library/djmax-clazziquai-edition/2OIP-C3.webp",
    "/psp-library/djmax-clazziquai-edition/OIP-C.webp",
    "/psp-library/djmax-clazziquai-edition/OIP-C2.webp"
  ]
}, {
  "id": "nba-ballers-rebound",
  "title": "NBA球员反击",
  "foreignTitle": "NBA Ballers Rebound",
  "cover": "/psp-library/nba-ballers-rebound/127874-title-NBA-Ballers-Rebound.jpg",
  "detailCover": "/psp-library/nba-ballers-rebound/127874-title-NBA-Ballers-Rebound.jpg",
  "boxCover": "/psp-library/nba-ballers-rebound/封面图.png",
  "genre": "SPG-体育",
  "cardGenre": "SPG",
  "publisher": "Midway",
  "releaseDate": "2006-05-09",
  "requiredSystem": "待确认",
  "language": "英",
  "cardLanguage": "英文",
  "downloadUrl": "https://pan.baidu.com/s/15sVU4JQRgHx-g8lPhJPPIw?pwd=9999",
  "videoUrl": "https://v.douyin.com/PjmrQdEZ8GA",
  "updatedAt": "2026-09-24T15:58:00.783Z",
  "description": "本作是街头篮球题材游戏，主打热血夸张的 1V1 单挑玩法。游戏收录超级多的知名 NBA 球星，赛场风格随性不羁，摒弃正规赛事规则。玩家既可自建球员闯荡街头联赛，逐步成长为顶级球星，也能直接选用巨星展开对决。花式运球、暴扣绝杀等酷炫动作应有尽有，积攒能量还能释放专属必杀招式，同时支持本地联机对战，节奏紧凑刺激，带来爽快过瘾的街头竞技乐趣。",
  "screenshots": [
    "/psp-library/nba-ballers-rebound/Download-NBA-Ballers-Rebound-PPSSPP-ISO-Ukuran-Kecil-2.jpg",
    "/psp-library/nba-ballers-rebound/f86474a4-6a33-4b19-af93-dd87144f0959.png",
    "/psp-library/nba-ballers-rebound/NBA-Ballers-Rebound-PSP-1_.jpg",
    "/psp-library/nba-ballers-rebound/NBA-Ballers-Rebound-PSP-_.jpg",
    "/psp-library/nba-ballers-rebound/OIP-C1.webp"
  ]
}, {
  "id": "valkyrie-profile-lenneth",
  "title": "北欧女神：蕾娜斯",
  "foreignTitle": "Valkyrie Profile – Lenneth",
  "cover": "/psp-library/valkyrie-profile-lenneth/1d63ffb4984c4e748076bcd899bd5cef.webp",
  "detailCover": "/psp-library/valkyrie-profile-lenneth/1d63ffb4984c4e748076bcd899bd5cef.webp",
  "boxCover": "/psp-library/valkyrie-profile-lenneth/封面图.png",
  "genre": "RPG-角色扮演",
  "cardGenre": "RPG",
  "publisher": "SQUARE ENIX",
  "releaseDate": "2006-03-02",
  "requiredSystem": "待确认",
  "language": "中、日、英",
  "cardLanguage": "中文",
  "downloadUrl": "https://pan.baidu.com/s/1I0QQM_rWlUDe3TChJaDTxQ?pwd=9999",
  "videoUrl": "https://v.douyin.com/57aBVe8AQv0",
  "updatedAt": "2026-09-24T15:58:00.788Z",
  "description": "本作是 SE 发行、tri-Ace 制作的经典 RPG，2006 年登陆 PSP，为 PS 初代移植强化版。玩家化身女武神蕾娜丝，遵照奥丁指令游历人间收集勇士英灵，备战诸神黄昏。游戏拥有独特分键连段战斗、平台跳跃式迷宫探索，多分支剧情搭配三种结局，配乐恢弘动人。PSP 版新增宽屏显示与追加 CG，剧情悲壮深刻，系统设计极具创意，是 PSP 公认殿堂级日式角色扮演佳作。",
  "screenshots": [
    "/psp-library/valkyrie-profile-lenneth/2f647f3b91724c3baf645e4c8d1ecd53.jpg",
    "/psp-library/valkyrie-profile-lenneth/ff0e06977fb372babf459c0054a1ec1a.jpg",
    "/psp-library/valkyrie-profile-lenneth/OIP-C.webp"
  ]
}]
