/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as RandomRouteImport } from './routes/random'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapContentDotxmlRouteImport } from './routes/sitemap-content[.]xml'
import { Route as SitemapGames1DotxmlRouteImport } from './routes/sitemap-games-1[.]xml'
import { Route as SitemapGames2DotxmlRouteImport } from './routes/sitemap-games-2[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as XRouteImport } from './routes/x'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocalePRORouteImport } from './routes/$locale.PRO'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleAllGamesRouteImport } from './routes/$locale.all-games'
import { Route as LocaleArcadeRouteImport } from './routes/$locale.arcade'
import { Route as LocaleBlogRouteImport } from './routes/$locale.blog'
import { Route as LocaleCoinChallengeRouteImport } from './routes/$locale.coin-challenge'
import { Route as LocaleDealsRouteImport } from './routes/$locale.deals'
import { Route as LocaleGhostHunterRouteImport } from './routes/$locale.ghost-hunter'
import { Route as LocaleLiveRouteImport } from './routes/$locale.live'
import { Route as LocaleLuckyGrandSlamRouteImport } from './routes/$locale.lucky-grand-slam'
import { Route as LocaleOriginalGamesRouteImport } from './routes/$locale.original-games'
import { Route as LocalePlayMyRomRouteImport } from './routes/$locale.play-my-rom'
import { Route as LocalePrivacyPolicyRouteImport } from './routes/$locale.privacy-policy'
import { Route as LocaleRandomRouteImport } from './routes/$locale.random'
import { Route as LocaleRedBlueArenaRouteImport } from './routes/$locale.red-blue-arena'
import { Route as LocaleSearchRouteImport } from './routes/$locale.search'
import { Route as LocaleTermsOfServiceRouteImport } from './routes/$locale.terms-of-service'
import { Route as LocaleThemeModeRouteImport } from './routes/$locale.theme-mode'
import { Route as LocaleWantedRouteImport } from './routes/$locale.wanted'
import { Route as ApiCoinChallengeCommunityRouteImport } from './routes/api.coin-challenge-community'
import { Route as ApiCoinRankingsRouteImport } from './routes/api.coin-rankings'
import { Route as ApiLocaleSuggestionRouteImport } from './routes/api/locale-suggestion'
import { Route as ApiMemberRouteImport } from './routes/api.member'
import { Route as ApiPspLikesRouteImport } from './routes/api.psp-likes'
import { Route as ApiShareImageRouteImport } from './routes/api/share-image'
import { Route as ApiWantedRouteImport } from './routes/api.wanted'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as LocaleBlogBlogIdRouteImport } from './routes/$locale.blog.$blogId'
import { Route as LocaleCollectionsCollectionIdRouteImport } from './routes/$locale.collections.$collectionId'
import { Route as LocaleGamesGameIdRouteImport } from './routes/$locale.games.$gameId'
import { Route as LocalePlatformPlatformIdRouteImport } from './routes/$locale.platform.$platformId'
import { Route as LocaleRankingsRankingIdRouteImport } from './routes/$locale.rankings.$rankingId'
import { Route as LocaleRankingsCoinsRouteImport } from './routes/$locale.rankings.coins'
import { Route as UsernameArticleStatusidRouteImport } from './routes/$username/article/$statusid'
import { Route as UsernameStatusStatusidRouteImport } from './routes/$username/status/$statusid'
import { Route as GamesGameIdPlayRouteImport } from './routes/games/$gameId/play'
import { Route as LocaleDealsSteamSteamAppIdRouteImport } from './routes/$locale.deals_.steam.$steamAppId'
import { Route as LocaleGamesGameIdPlayRouteImport } from './routes/$locale.games.$gameId.play'
import { Route as LocalePlatformPspGameIdRouteImport } from './routes/$locale.platform.psp.$gameId'
import { Route as LocalePlatformSwitchGameIdRouteImport } from './routes/$locale.platform.switch.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapContentDotxmlRoute = SitemapContentDotxmlRouteImport.update({
  id: '/sitemap-content.xml',
  path: '/sitemap-content.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapGames1DotxmlRoute = SitemapGames1DotxmlRouteImport.update({
  id: '/sitemap-games-1.xml',
  path: '/sitemap-games-1.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapGames2DotxmlRoute = SitemapGames2DotxmlRouteImport.update({
  id: '/sitemap-games-2.xml',
  path: '/sitemap-games-2.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePRORoute = LocalePRORouteImport.update({
  id: '/PRO',
  path: '/PRO',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAllGamesRoute = LocaleAllGamesRouteImport.update({
  id: '/all-games',
  path: '/all-games',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleArcadeRoute = LocaleArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogRoute = LocaleBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCoinChallengeRoute = LocaleCoinChallengeRouteImport.update({
  id: '/coin-challenge',
  path: '/coin-challenge',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDealsRoute = LocaleDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGhostHunterRoute = LocaleGhostHunterRouteImport.update({
  id: '/ghost-hunter',
  path: '/ghost-hunter',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLiveRoute = LocaleLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLuckyGrandSlamRoute = LocaleLuckyGrandSlamRouteImport.update({
  id: '/lucky-grand-slam',
  path: '/lucky-grand-slam',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOriginalGamesRoute = LocaleOriginalGamesRouteImport.update({
  id: '/original-games',
  path: '/original-games',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePlayMyRomRoute = LocalePlayMyRomRouteImport.update({
  id: '/play-my-rom',
  path: '/play-my-rom',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyPolicyRoute = LocalePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRandomRoute = LocaleRandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRedBlueArenaRoute = LocaleRedBlueArenaRouteImport.update({
  id: '/red-blue-arena',
  path: '/red-blue-arena',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSearchRoute = LocaleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsOfServiceRoute = LocaleTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleThemeModeRoute = LocaleThemeModeRouteImport.update({
  id: '/theme-mode',
  path: '/theme-mode',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleWantedRoute = LocaleWantedRouteImport.update({
  id: '/wanted',
  path: '/wanted',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiCoinChallengeCommunityRoute =
  ApiCoinChallengeCommunityRouteImport.update({
    id: '/api/coin-challenge-community',
    path: '/api/coin-challenge-community',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCoinRankingsRoute = ApiCoinRankingsRouteImport.update({
  id: '/api/coin-rankings',
  path: '/api/coin-rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocaleSuggestionRoute = ApiLocaleSuggestionRouteImport.update({
  id: '/api/locale-suggestion',
  path: '/api/locale-suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemberRoute = ApiMemberRouteImport.update({
  id: '/api/member',
  path: '/api/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPspLikesRoute = ApiPspLikesRouteImport.update({
  id: '/api/psp-likes',
  path: '/api/psp-likes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareImageRoute = ApiShareImageRouteImport.update({
  id: '/api/share-image',
  path: '/api/share-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWantedRoute = ApiWantedRouteImport.update({
  id: '/api/wanted',
  path: '/api/wanted',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogBlogIdRoute = LocaleBlogBlogIdRouteImport.update({
  id: '/$blogId',
  path: '/$blogId',
  getParentRoute: () => LocaleBlogRoute,
} as any)
const LocaleCollectionsCollectionIdRoute =
  LocaleCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleGamesGameIdRoute = LocaleGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePlatformPlatformIdRoute =
  LocalePlatformPlatformIdRouteImport.update({
    id: '/platform/$platformId',
    path: '/platform/$platformId',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleRankingsRankingIdRoute = LocaleRankingsRankingIdRouteImport.update({
  id: '/rankings/$rankingId',
  path: '/rankings/$rankingId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRankingsCoinsRoute = LocaleRankingsCoinsRouteImport.update({
  id: '/rankings/coins',
  path: '/rankings/coins',
  getParentRoute: () => LocaleRoute,
} as any)
const UsernameArticleStatusidRoute = UsernameArticleStatusidRouteImport.update({
  id: '/$username/article/$statusid',
  path: '/$username/article/$statusid',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameStatusStatusidRoute = UsernameStatusStatusidRouteImport.update({
  id: '/$username/status/$statusid',
  path: '/$username/status/$statusid',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdPlayRoute = GamesGameIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GamesGameIdRoute,
} as any)
const LocaleDealsSteamSteamAppIdRoute =
  LocaleDealsSteamSteamAppIdRouteImport.update({
    id: '/deals_/steam/$steamAppId',
    path: '/deals/steam/$steamAppId',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleGamesGameIdPlayRoute = LocaleGamesGameIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => LocaleGamesGameIdRoute,
} as any)
const LocalePlatformPspGameIdRoute = LocalePlatformPspGameIdRouteImport.update({
  id: '/platform/psp/$gameId',
  path: '/platform/psp/$gameId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePlatformSwitchGameIdRoute =
  LocalePlatformSwitchGameIdRouteImport.update({
    id: '/platform/switch/$gameId',
    path: '/platform/switch/$gameId',
    getParentRoute: () => LocaleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/random': typeof RandomRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-content.xml': typeof SitemapContentDotxmlRoute
  '/sitemap-games-1.xml': typeof SitemapGames1DotxmlRoute
  '/sitemap-games-2.xml': typeof SitemapGames2DotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/x': typeof XRoute
  '/$locale/PRO': typeof LocalePRORoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/all-games': typeof LocaleAllGamesRoute
  '/$locale/arcade': typeof LocaleArcadeRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/coin-challenge': typeof LocaleCoinChallengeRoute
  '/$locale/deals': typeof LocaleDealsRoute
  '/$locale/ghost-hunter': typeof LocaleGhostHunterRoute
  '/$locale/live': typeof LocaleLiveRoute
  '/$locale/lucky-grand-slam': typeof LocaleLuckyGrandSlamRoute
  '/$locale/original-games': typeof LocaleOriginalGamesRoute
  '/$locale/play-my-rom': typeof LocalePlayMyRomRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/random': typeof LocaleRandomRoute
  '/$locale/red-blue-arena': typeof LocaleRedBlueArenaRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/$locale/theme-mode': typeof LocaleThemeModeRoute
  '/$locale/wanted': typeof LocaleWantedRoute
  '/api/coin-challenge-community': typeof ApiCoinChallengeCommunityRoute
  '/api/coin-rankings': typeof ApiCoinRankingsRoute
  '/api/locale-suggestion': typeof ApiLocaleSuggestionRoute
  '/api/member': typeof ApiMemberRoute
  '/api/psp-likes': typeof ApiPspLikesRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/api/wanted': typeof ApiWantedRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$blogId': typeof LocaleBlogBlogIdRoute
  '/$locale/collections/$collectionId': typeof LocaleCollectionsCollectionIdRoute
  '/$locale/games/$gameId': typeof LocaleGamesGameIdRouteWithChildren
  '/$locale/platform/$platformId': typeof LocalePlatformPlatformIdRoute
  '/$locale/rankings/$rankingId': typeof LocaleRankingsRankingIdRoute
  '/$locale/rankings/coins': typeof LocaleRankingsCoinsRoute
  '/$username/article/$statusid': typeof UsernameArticleStatusidRoute
  '/$username/status/$statusid': typeof UsernameStatusStatusidRoute
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/$locale/deals/steam/$steamAppId': typeof LocaleDealsSteamSteamAppIdRoute
  '/$locale/games/$gameId/play': typeof LocaleGamesGameIdPlayRoute
  '/$locale/platform/psp/$gameId': typeof LocalePlatformPspGameIdRoute
  '/$locale/platform/switch/$gameId': typeof LocalePlatformSwitchGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/random': typeof RandomRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-content.xml': typeof SitemapContentDotxmlRoute
  '/sitemap-games-1.xml': typeof SitemapGames1DotxmlRoute
  '/sitemap-games-2.xml': typeof SitemapGames2DotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/x': typeof XRoute
  '/$locale/PRO': typeof LocalePRORoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/all-games': typeof LocaleAllGamesRoute
  '/$locale/arcade': typeof LocaleArcadeRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/coin-challenge': typeof LocaleCoinChallengeRoute
  '/$locale/deals': typeof LocaleDealsRoute
  '/$locale/ghost-hunter': typeof LocaleGhostHunterRoute
  '/$locale/live': typeof LocaleLiveRoute
  '/$locale/lucky-grand-slam': typeof LocaleLuckyGrandSlamRoute
  '/$locale/original-games': typeof LocaleOriginalGamesRoute
  '/$locale/play-my-rom': typeof LocalePlayMyRomRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/random': typeof LocaleRandomRoute
  '/$locale/red-blue-arena': typeof LocaleRedBlueArenaRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/$locale/theme-mode': typeof LocaleThemeModeRoute
  '/$locale/wanted': typeof LocaleWantedRoute
  '/api/coin-challenge-community': typeof ApiCoinChallengeCommunityRoute
  '/api/coin-rankings': typeof ApiCoinRankingsRoute
  '/api/locale-suggestion': typeof ApiLocaleSuggestionRoute
  '/api/member': typeof ApiMemberRoute
  '/api/psp-likes': typeof ApiPspLikesRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/api/wanted': typeof ApiWantedRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$blogId': typeof LocaleBlogBlogIdRoute
  '/$locale/collections/$collectionId': typeof LocaleCollectionsCollectionIdRoute
  '/$locale/games/$gameId': typeof LocaleGamesGameIdRouteWithChildren
  '/$locale/platform/$platformId': typeof LocalePlatformPlatformIdRoute
  '/$locale/rankings/$rankingId': typeof LocaleRankingsRankingIdRoute
  '/$locale/rankings/coins': typeof LocaleRankingsCoinsRoute
  '/$username/article/$statusid': typeof UsernameArticleStatusidRoute
  '/$username/status/$statusid': typeof UsernameStatusStatusidRoute
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/$locale/deals/steam/$steamAppId': typeof LocaleDealsSteamSteamAppIdRoute
  '/$locale/games/$gameId/play': typeof LocaleGamesGameIdPlayRoute
  '/$locale/platform/psp/$gameId': typeof LocalePlatformPspGameIdRoute
  '/$locale/platform/switch/$gameId': typeof LocalePlatformSwitchGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/random': typeof RandomRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-content.xml': typeof SitemapContentDotxmlRoute
  '/sitemap-games-1.xml': typeof SitemapGames1DotxmlRoute
  '/sitemap-games-2.xml': typeof SitemapGames2DotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/x': typeof XRoute
  '/$locale/PRO': typeof LocalePRORoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/all-games': typeof LocaleAllGamesRoute
  '/$locale/arcade': typeof LocaleArcadeRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/coin-challenge': typeof LocaleCoinChallengeRoute
  '/$locale/deals': typeof LocaleDealsRoute
  '/$locale/ghost-hunter': typeof LocaleGhostHunterRoute
  '/$locale/live': typeof LocaleLiveRoute
  '/$locale/lucky-grand-slam': typeof LocaleLuckyGrandSlamRoute
  '/$locale/original-games': typeof LocaleOriginalGamesRoute
  '/$locale/play-my-rom': typeof LocalePlayMyRomRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/random': typeof LocaleRandomRoute
  '/$locale/red-blue-arena': typeof LocaleRedBlueArenaRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/terms-of-service': typeof LocaleTermsOfServiceRoute
  '/$locale/theme-mode': typeof LocaleThemeModeRoute
  '/$locale/wanted': typeof LocaleWantedRoute
  '/api/coin-challenge-community': typeof ApiCoinChallengeCommunityRoute
  '/api/coin-rankings': typeof ApiCoinRankingsRoute
  '/api/locale-suggestion': typeof ApiLocaleSuggestionRoute
  '/api/member': typeof ApiMemberRoute
  '/api/psp-likes': typeof ApiPspLikesRoute
  '/api/share-image': typeof ApiShareImageRoute
  '/api/wanted': typeof ApiWantedRoute
  '/games/$gameId': typeof GamesGameIdRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$blogId': typeof LocaleBlogBlogIdRoute
  '/$locale/collections/$collectionId': typeof LocaleCollectionsCollectionIdRoute
  '/$locale/games/$gameId': typeof LocaleGamesGameIdRouteWithChildren
  '/$locale/platform/$platformId': typeof LocalePlatformPlatformIdRoute
  '/$locale/rankings/$rankingId': typeof LocaleRankingsRankingIdRoute
  '/$locale/rankings/coins': typeof LocaleRankingsCoinsRoute
  '/$username/article/$statusid': typeof UsernameArticleStatusidRoute
  '/$username/status/$statusid': typeof UsernameStatusStatusidRoute
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/$locale/deals_/steam/$steamAppId': typeof LocaleDealsSteamSteamAppIdRoute
  '/$locale/games/$gameId/play': typeof LocaleGamesGameIdPlayRoute
  '/$locale/platform/psp/$gameId': typeof LocalePlatformPspGameIdRoute
  '/$locale/platform/switch/$gameId': typeof LocalePlatformSwitchGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/manifest.webmanifest'
    | '/random'
    | '/robots.txt'
    | '/sitemap-content.xml'
    | '/sitemap-games-1.xml'
    | '/sitemap-games-2.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/x'
    | '/$locale/PRO'
    | '/$locale/about'
    | '/$locale/all-games'
    | '/$locale/arcade'
    | '/$locale/blog'
    | '/$locale/coin-challenge'
    | '/$locale/deals'
    | '/$locale/ghost-hunter'
    | '/$locale/live'
    | '/$locale/lucky-grand-slam'
    | '/$locale/original-games'
    | '/$locale/play-my-rom'
    | '/$locale/privacy-policy'
    | '/$locale/random'
    | '/$locale/red-blue-arena'
    | '/$locale/search'
    | '/$locale/terms-of-service'
    | '/$locale/theme-mode'
    | '/$locale/wanted'
    | '/api/coin-challenge-community'
    | '/api/coin-rankings'
    | '/api/locale-suggestion'
    | '/api/member'
    | '/api/psp-likes'
    | '/api/share-image'
    | '/api/wanted'
    | '/games/$gameId'
    | '/$locale/'
    | '/$locale/blog/$blogId'
    | '/$locale/collections/$collectionId'
    | '/$locale/games/$gameId'
    | '/$locale/platform/$platformId'
    | '/$locale/rankings/$rankingId'
    | '/$locale/rankings/coins'
    | '/$username/article/$statusid'
    | '/$username/status/$statusid'
    | '/games/$gameId/play'
    | '/$locale/deals/steam/$steamAppId'
    | '/$locale/games/$gameId/play'
    | '/$locale/platform/psp/$gameId'
    | '/$locale/platform/switch/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifest.webmanifest'
    | '/random'
    | '/robots.txt'
    | '/sitemap-content.xml'
    | '/sitemap-games-1.xml'
    | '/sitemap-games-2.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/x'
    | '/$locale/PRO'
    | '/$locale/about'
    | '/$locale/all-games'
    | '/$locale/arcade'
    | '/$locale/blog'
    | '/$locale/coin-challenge'
    | '/$locale/deals'
    | '/$locale/ghost-hunter'
    | '/$locale/live'
    | '/$locale/lucky-grand-slam'
    | '/$locale/original-games'
    | '/$locale/play-my-rom'
    | '/$locale/privacy-policy'
    | '/$locale/random'
    | '/$locale/red-blue-arena'
    | '/$locale/search'
    | '/$locale/terms-of-service'
    | '/$locale/theme-mode'
    | '/$locale/wanted'
    | '/api/coin-challenge-community'
    | '/api/coin-rankings'
    | '/api/locale-suggestion'
    | '/api/member'
    | '/api/psp-likes'
    | '/api/share-image'
    | '/api/wanted'
    | '/games/$gameId'
    | '/$locale'
    | '/$locale/blog/$blogId'
    | '/$locale/collections/$collectionId'
    | '/$locale/games/$gameId'
    | '/$locale/platform/$platformId'
    | '/$locale/rankings/$rankingId'
    | '/$locale/rankings/coins'
    | '/$username/article/$statusid'
    | '/$username/status/$statusid'
    | '/games/$gameId/play'
    | '/$locale/deals/steam/$steamAppId'
    | '/$locale/games/$gameId/play'
    | '/$locale/platform/psp/$gameId'
    | '/$locale/platform/switch/$gameId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/manifest.webmanifest'
    | '/random'
    | '/robots.txt'
    | '/sitemap-content.xml'
    | '/sitemap-games-1.xml'
    | '/sitemap-games-2.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/x'
    | '/$locale/PRO'
    | '/$locale/about'
    | '/$locale/all-games'
    | '/$locale/arcade'
    | '/$locale/blog'
    | '/$locale/coin-challenge'
    | '/$locale/deals'
    | '/$locale/ghost-hunter'
    | '/$locale/live'
    | '/$locale/lucky-grand-slam'
    | '/$locale/original-games'
    | '/$locale/play-my-rom'
    | '/$locale/privacy-policy'
    | '/$locale/random'
    | '/$locale/red-blue-arena'
    | '/$locale/search'
    | '/$locale/terms-of-service'
    | '/$locale/theme-mode'
    | '/$locale/wanted'
    | '/api/coin-challenge-community'
    | '/api/coin-rankings'
    | '/api/locale-suggestion'
    | '/api/member'
    | '/api/psp-likes'
    | '/api/share-image'
    | '/api/wanted'
    | '/games/$gameId'
    | '/$locale/'
    | '/$locale/blog/$blogId'
    | '/$locale/collections/$collectionId'
    | '/$locale/games/$gameId'
    | '/$locale/platform/$platformId'
    | '/$locale/rankings/$rankingId'
    | '/$locale/rankings/coins'
    | '/$username/article/$statusid'
    | '/$username/status/$statusid'
    | '/games/$gameId/play'
    | '/$locale/deals_/steam/$steamAppId'
    | '/$locale/games/$gameId/play'
    | '/$locale/platform/psp/$gameId'
    | '/$locale/platform/switch/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  RandomRoute: typeof RandomRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapContentDotxmlRoute: typeof SitemapContentDotxmlRoute
  SitemapGames1DotxmlRoute: typeof SitemapGames1DotxmlRoute
  SitemapGames2DotxmlRoute: typeof SitemapGames2DotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  XRoute: typeof XRoute
  ApiCoinChallengeCommunityRoute: typeof ApiCoinChallengeCommunityRoute
  ApiCoinRankingsRoute: typeof ApiCoinRankingsRoute
  ApiLocaleSuggestionRoute: typeof ApiLocaleSuggestionRoute
  ApiMemberRoute: typeof ApiMemberRoute
  ApiPspLikesRoute: typeof ApiPspLikesRoute
  ApiShareImageRoute: typeof ApiShareImageRoute
  ApiWantedRoute: typeof ApiWantedRoute
  GamesGameIdRoute: typeof GamesGameIdRouteWithChildren
  UsernameArticleStatusidRoute: typeof UsernameArticleStatusidRoute
  UsernameStatusStatusidRoute: typeof UsernameStatusStatusidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-content.xml': {
      id: '/sitemap-content.xml'
      path: '/sitemap-content.xml'
      fullPath: '/sitemap-content.xml'
      preLoaderRoute: typeof SitemapContentDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-games-1.xml': {
      id: '/sitemap-games-1.xml'
      path: '/sitemap-games-1.xml'
      fullPath: '/sitemap-games-1.xml'
      preLoaderRoute: typeof SitemapGames1DotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-games-2.xml': {
      id: '/sitemap-games-2.xml'
      path: '/sitemap-games-2.xml'
      fullPath: '/sitemap-games-2.xml'
      preLoaderRoute: typeof SitemapGames2DotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/PRO': {
      id: '/$locale/PRO'
      path: '/PRO'
      fullPath: '/$locale/PRO'
      preLoaderRoute: typeof LocalePRORouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/all-games': {
      id: '/$locale/all-games'
      path: '/all-games'
      fullPath: '/$locale/all-games'
      preLoaderRoute: typeof LocaleAllGamesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/arcade': {
      id: '/$locale/arcade'
      path: '/arcade'
      fullPath: '/$locale/arcade'
      preLoaderRoute: typeof LocaleArcadeRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog': {
      id: '/$locale/blog'
      path: '/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/coin-challenge': {
      id: '/$locale/coin-challenge'
      path: '/coin-challenge'
      fullPath: '/$locale/coin-challenge'
      preLoaderRoute: typeof LocaleCoinChallengeRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/deals': {
      id: '/$locale/deals'
      path: '/deals'
      fullPath: '/$locale/deals'
      preLoaderRoute: typeof LocaleDealsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ghost-hunter': {
      id: '/$locale/ghost-hunter'
      path: '/ghost-hunter'
      fullPath: '/$locale/ghost-hunter'
      preLoaderRoute: typeof LocaleGhostHunterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/live': {
      id: '/$locale/live'
      path: '/live'
      fullPath: '/$locale/live'
      preLoaderRoute: typeof LocaleLiveRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/lucky-grand-slam': {
      id: '/$locale/lucky-grand-slam'
      path: '/lucky-grand-slam'
      fullPath: '/$locale/lucky-grand-slam'
      preLoaderRoute: typeof LocaleLuckyGrandSlamRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/original-games': {
      id: '/$locale/original-games'
      path: '/original-games'
      fullPath: '/$locale/original-games'
      preLoaderRoute: typeof LocaleOriginalGamesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/play-my-rom': {
      id: '/$locale/play-my-rom'
      path: '/play-my-rom'
      fullPath: '/$locale/play-my-rom'
      preLoaderRoute: typeof LocalePlayMyRomRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy-policy': {
      id: '/$locale/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$locale/privacy-policy'
      preLoaderRoute: typeof LocalePrivacyPolicyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/random': {
      id: '/$locale/random'
      path: '/random'
      fullPath: '/$locale/random'
      preLoaderRoute: typeof LocaleRandomRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/red-blue-arena': {
      id: '/$locale/red-blue-arena'
      path: '/red-blue-arena'
      fullPath: '/$locale/red-blue-arena'
      preLoaderRoute: typeof LocaleRedBlueArenaRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/search': {
      id: '/$locale/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleSearchRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms-of-service': {
      id: '/$locale/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/$locale/terms-of-service'
      preLoaderRoute: typeof LocaleTermsOfServiceRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/theme-mode': {
      id: '/$locale/theme-mode'
      path: '/theme-mode'
      fullPath: '/$locale/theme-mode'
      preLoaderRoute: typeof LocaleThemeModeRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/wanted': {
      id: '/$locale/wanted'
      path: '/wanted'
      fullPath: '/$locale/wanted'
      preLoaderRoute: typeof LocaleWantedRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/coin-challenge-community': {
      id: '/api/coin-challenge-community'
      path: '/api/coin-challenge-community'
      fullPath: '/api/coin-challenge-community'
      preLoaderRoute: typeof ApiCoinChallengeCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coin-rankings': {
      id: '/api/coin-rankings'
      path: '/api/coin-rankings'
      fullPath: '/api/coin-rankings'
      preLoaderRoute: typeof ApiCoinRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locale-suggestion': {
      id: '/api/locale-suggestion'
      path: '/api/locale-suggestion'
      fullPath: '/api/locale-suggestion'
      preLoaderRoute: typeof ApiLocaleSuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/member': {
      id: '/api/member'
      path: '/api/member'
      fullPath: '/api/member'
      preLoaderRoute: typeof ApiMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/psp-likes': {
      id: '/api/psp-likes'
      path: '/api/psp-likes'
      fullPath: '/api/psp-likes'
      preLoaderRoute: typeof ApiPspLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share-image': {
      id: '/api/share-image'
      path: '/api/share-image'
      fullPath: '/api/share-image'
      preLoaderRoute: typeof ApiShareImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wanted': {
      id: '/api/wanted'
      path: '/api/wanted'
      fullPath: '/api/wanted'
      preLoaderRoute: typeof ApiWantedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$blogId': {
      id: '/$locale/blog/$blogId'
      path: '/$blogId'
      fullPath: '/$locale/blog/$blogId'
      preLoaderRoute: typeof LocaleBlogBlogIdRouteImport
      parentRoute: typeof LocaleBlogRoute
    }
    '/$locale/collections/$collectionId': {
      id: '/$locale/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/$locale/collections/$collectionId'
      preLoaderRoute: typeof LocaleCollectionsCollectionIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/games/$gameId': {
      id: '/$locale/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/$locale/games/$gameId'
      preLoaderRoute: typeof LocaleGamesGameIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/platform/$platformId': {
      id: '/$locale/platform/$platformId'
      path: '/platform/$platformId'
      fullPath: '/$locale/platform/$platformId'
      preLoaderRoute: typeof LocalePlatformPlatformIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/rankings/$rankingId': {
      id: '/$locale/rankings/$rankingId'
      path: '/rankings/$rankingId'
      fullPath: '/$locale/rankings/$rankingId'
      preLoaderRoute: typeof LocaleRankingsRankingIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/rankings/coins': {
      id: '/$locale/rankings/coins'
      path: '/rankings/coins'
      fullPath: '/$locale/rankings/coins'
      preLoaderRoute: typeof LocaleRankingsCoinsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$username/article/$statusid': {
      id: '/$username/article/$statusid'
      path: '/$username/article/$statusid'
      fullPath: '/$username/article/$statusid'
      preLoaderRoute: typeof UsernameArticleStatusidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/status/$statusid': {
      id: '/$username/status/$statusid'
      path: '/$username/status/$statusid'
      fullPath: '/$username/status/$statusid'
      preLoaderRoute: typeof UsernameStatusStatusidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/play': {
      id: '/games/$gameId/play'
      path: '/play'
      fullPath: '/games/$gameId/play'
      preLoaderRoute: typeof GamesGameIdPlayRouteImport
      parentRoute: typeof GamesGameIdRoute
    }
    '/$locale/deals_/steam/$steamAppId': {
      id: '/$locale/deals_/steam/$steamAppId'
      path: '/deals/steam/$steamAppId'
      fullPath: '/$locale/deals/steam/$steamAppId'
      preLoaderRoute: typeof LocaleDealsSteamSteamAppIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/games/$gameId/play': {
      id: '/$locale/games/$gameId/play'
      path: '/play'
      fullPath: '/$locale/games/$gameId/play'
      preLoaderRoute: typeof LocaleGamesGameIdPlayRouteImport
      parentRoute: typeof LocaleGamesGameIdRoute
    }
    '/$locale/platform/psp/$gameId': {
      id: '/$locale/platform/psp/$gameId'
      path: '/platform/psp/$gameId'
      fullPath: '/$locale/platform/psp/$gameId'
      preLoaderRoute: typeof LocalePlatformPspGameIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/platform/switch/$gameId': {
      id: '/$locale/platform/switch/$gameId'
      path: '/platform/switch/$gameId'
      fullPath: '/$locale/platform/switch/$gameId'
      preLoaderRoute: typeof LocalePlatformSwitchGameIdRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleBlogRouteChildren {
  LocaleBlogBlogIdRoute: typeof LocaleBlogBlogIdRoute
}

const LocaleBlogRouteChildren: LocaleBlogRouteChildren = {
  LocaleBlogBlogIdRoute: LocaleBlogBlogIdRoute,
}

const LocaleBlogRouteWithChildren = LocaleBlogRoute._addFileChildren(
  LocaleBlogRouteChildren,
)

interface LocaleGamesGameIdRouteChildren {
  LocaleGamesGameIdPlayRoute: typeof LocaleGamesGameIdPlayRoute
}

const LocaleGamesGameIdRouteChildren: LocaleGamesGameIdRouteChildren = {
  LocaleGamesGameIdPlayRoute: LocaleGamesGameIdPlayRoute,
}

const LocaleGamesGameIdRouteWithChildren =
  LocaleGamesGameIdRoute._addFileChildren(LocaleGamesGameIdRouteChildren)

interface LocaleRouteChildren {
  LocalePRORoute: typeof LocalePRORoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleAllGamesRoute: typeof LocaleAllGamesRoute
  LocaleArcadeRoute: typeof LocaleArcadeRoute
  LocaleBlogRoute: typeof LocaleBlogRouteWithChildren
  LocaleCoinChallengeRoute: typeof LocaleCoinChallengeRoute
  LocaleDealsRoute: typeof LocaleDealsRoute
  LocaleGhostHunterRoute: typeof LocaleGhostHunterRoute
  LocaleLiveRoute: typeof LocaleLiveRoute
  LocaleLuckyGrandSlamRoute: typeof LocaleLuckyGrandSlamRoute
  LocaleOriginalGamesRoute: typeof LocaleOriginalGamesRoute
  LocalePlayMyRomRoute: typeof LocalePlayMyRomRoute
  LocalePrivacyPolicyRoute: typeof LocalePrivacyPolicyRoute
  LocaleRandomRoute: typeof LocaleRandomRoute
  LocaleRedBlueArenaRoute: typeof LocaleRedBlueArenaRoute
  LocaleSearchRoute: typeof LocaleSearchRoute
  LocaleTermsOfServiceRoute: typeof LocaleTermsOfServiceRoute
  LocaleThemeModeRoute: typeof LocaleThemeModeRoute
  LocaleWantedRoute: typeof LocaleWantedRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleCollectionsCollectionIdRoute: typeof LocaleCollectionsCollectionIdRoute
  LocaleGamesGameIdRoute: typeof LocaleGamesGameIdRouteWithChildren
  LocalePlatformPlatformIdRoute: typeof LocalePlatformPlatformIdRoute
  LocaleRankingsRankingIdRoute: typeof LocaleRankingsRankingIdRoute
  LocaleRankingsCoinsRoute: typeof LocaleRankingsCoinsRoute
  LocaleDealsSteamSteamAppIdRoute: typeof LocaleDealsSteamSteamAppIdRoute
  LocalePlatformPspGameIdRoute: typeof LocalePlatformPspGameIdRoute
  LocalePlatformSwitchGameIdRoute: typeof LocalePlatformSwitchGameIdRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocalePRORoute: LocalePRORoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleAllGamesRoute: LocaleAllGamesRoute,
  LocaleArcadeRoute: LocaleArcadeRoute,
  LocaleBlogRoute: LocaleBlogRouteWithChildren,
  LocaleCoinChallengeRoute: LocaleCoinChallengeRoute,
  LocaleDealsRoute: LocaleDealsRoute,
  LocaleGhostHunterRoute: LocaleGhostHunterRoute,
  LocaleLiveRoute: LocaleLiveRoute,
  LocaleLuckyGrandSlamRoute: LocaleLuckyGrandSlamRoute,
  LocaleOriginalGamesRoute: LocaleOriginalGamesRoute,
  LocalePlayMyRomRoute: LocalePlayMyRomRoute,
  LocalePrivacyPolicyRoute: LocalePrivacyPolicyRoute,
  LocaleRandomRoute: LocaleRandomRoute,
  LocaleRedBlueArenaRoute: LocaleRedBlueArenaRoute,
  LocaleSearchRoute: LocaleSearchRoute,
  LocaleTermsOfServiceRoute: LocaleTermsOfServiceRoute,
  LocaleThemeModeRoute: LocaleThemeModeRoute,
  LocaleWantedRoute: LocaleWantedRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleCollectionsCollectionIdRoute: LocaleCollectionsCollectionIdRoute,
  LocaleGamesGameIdRoute: LocaleGamesGameIdRouteWithChildren,
  LocalePlatformPlatformIdRoute: LocalePlatformPlatformIdRoute,
  LocaleRankingsRankingIdRoute: LocaleRankingsRankingIdRoute,
  LocaleRankingsCoinsRoute: LocaleRankingsCoinsRoute,
  LocaleDealsSteamSteamAppIdRoute: LocaleDealsSteamSteamAppIdRoute,
  LocalePlatformPspGameIdRoute: LocalePlatformPspGameIdRoute,
  LocalePlatformSwitchGameIdRoute: LocalePlatformSwitchGameIdRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface GamesGameIdRouteChildren {
  GamesGameIdPlayRoute: typeof GamesGameIdPlayRoute
}

const GamesGameIdRouteChildren: GamesGameIdRouteChildren = {
  GamesGameIdPlayRoute: GamesGameIdPlayRoute,
}

const GamesGameIdRouteWithChildren = GamesGameIdRoute._addFileChildren(
  GamesGameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  RandomRoute: RandomRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapContentDotxmlRoute: SitemapContentDotxmlRoute,
  SitemapGames1DotxmlRoute: SitemapGames1DotxmlRoute,
  SitemapGames2DotxmlRoute: SitemapGames2DotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  XRoute: XRoute,
  ApiCoinChallengeCommunityRoute: ApiCoinChallengeCommunityRoute,
  ApiCoinRankingsRoute: ApiCoinRankingsRoute,
  ApiLocaleSuggestionRoute: ApiLocaleSuggestionRoute,
  ApiMemberRoute: ApiMemberRoute,
  ApiPspLikesRoute: ApiPspLikesRoute,
  ApiShareImageRoute: ApiShareImageRoute,
  ApiWantedRoute: ApiWantedRoute,
  GamesGameIdRoute: GamesGameIdRouteWithChildren,
  UsernameArticleStatusidRoute: UsernameArticleStatusidRoute,
  UsernameStatusStatusidRoute: UsernameStatusStatusidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
